'use client'
import { createContext, useContext, useState, useEffect } from 'react'

export type Lang = 'en' | 'fr'

// ── All UI strings ─────────────────────────────────────────────────────────────
const T = {
  en: {
    // Nav
    nav_navigate:    'Navigate',
    nav_dashboard:   'Dashboard',
    nav_board:       'Board',
    nav_table:       'Table',
    nav_approved:    'Approved',
    nav_samples:     'Samples',
    nav_team:        'Team',
    nav_profile:     'Profile',
    nav_templates:   'Templates',
    nav_settings:    'Settings',
    nav_newRecord:   '+ New Record',
    nav_signOut:     'Out',

    // Record Drawer
    drawer_details:       'Details',
    drawer_comments:      'Comments',
    drawer_history:       'History',
    drawer_edit:          '✏️ Edit',
    drawer_notify:        '✉ Notify',
    drawer_archive:       '📁 Archive',
    drawer_restore:       '📤 Restore',
    drawer_archived:      '📁 Archived',
    drawer_moveStage:     'MOVE STAGE',
    drawer_priority:      'PRIORITY',
    drawer_waitingOn:     'Waiting on:',
    drawer_notes:         'NOTES',
    drawer_feedback:      'LICENSOR FEEDBACK',
    drawer_attachments:   'ATTACHMENTS',
    drawer_upload:        '+ Upload',
    drawer_uploading:     'Uploading…',
    drawer_cover:         'COVER',
    drawer_setCover:      '⭐ Cover',
    drawer_open:          'Open ↗',
    drawer_addComment:    'Add a comment…',
    drawer_post:          'Post',
    drawer_noComments:    'No comments yet.',
    drawer_noHistory:     'No history yet.',
    drawer_brand:         'Brand',
    drawer_property:      'Property',
    drawer_productType:   'Product Type',
    drawer_gender:        'Gender',
    drawer_owner:         'Owner',
    drawer_contact:       'Contact',
    drawer_licensorRef:   'Licensor Ref',
    drawer_samples:       'Samples',
    drawer_submission:    'Submission',
    drawer_conceptApproval: 'Concept Approval',
    drawer_ppsPhotos:     'PPS Photos',
    drawer_ppsApproval:   'PPS Approval',
    drawer_sampleSent:    'Sample Sent',
    drawer_sampleApproval:'Sample Approval',
    drawer_techPack:      'Tech Pack',
    drawer_additionalLink:'Additional Link',
    drawer_deleteConfirm: 'Delete this record? This cannot be undone.',
    drawer_system:        'System',

    // Record Form
    form_internalRef:     'Internal Ref *',
    form_licensorRef:     'Main Licensor Ref',
    form_productName:     'Product Name *',
    form_productType:     'Product Type',
    form_gender:          'Gender',
    form_brand:           'Brand',
    form_property:        'Property',
    form_stage:           'Stage',
    form_priority:        'Priority',
    form_owner:           'Owner',
    form_waitingOn:       'Waiting On',
    form_contact:         'Contact',
    form_nextAction:      'Next Action',
    form_notes:           'Notes',
    form_feedback:        'Licensor Feedback',
    form_techPackLink:    'Tech Pack Link',
    form_additionalLink:  'Additional Link',
    form_submissionDate:  'Submission Date',
    form_samplesQty:      'Samples Qty',
    form_reminder:        '🔔 Follow-up Reminder',
    form_reminderDate:    'Reminder Date',
    form_reminderNote:    'Note (optional)',
    form_reminderDone:    'Mark reminder as done',
    form_unassigned:      '— Unassigned —',
    form_select:          '— Select —',
    form_addBrand:        '＋ Add new brand…',
    form_addProperty:     '＋ Add new property…',
    form_typeBrand:       'Type brand name…',
    form_typeProperty:    'Type property name…',
    form_reminderPlaceholder: 'e.g. Follow up with licensor for approval',
    form_attachClick:     'Click to attach images or files',
    form_attachSub:       'Will upload when record is saved',
    form_attachments:     'ATTACHMENTS',
    form_uploadFile:      '＋ Upload file',
    form_uploading:       'Uploading…',
    form_save:            'Save',
    form_saving:          'Saving…',
    form_cancel:          'Cancel',

    // Dashboard
    dash_activeRecords:   'Active Records',
    dash_fullyApproved:   'Fully Approved',
    dash_remindersDue:    'Reminders Due',
    dash_upcomingWeek:    'upcoming this week',
    dash_noUpcoming:      'No upcoming reminders',
    dash_awaitingLicensor:'Awaiting Licensor',
    dash_awaitingFull:    'awaiting approval',
    dash_overdue:         '🔴 Overdue',
    dash_dueToday:        '🟡 Due Today',
    dash_upcoming:        '🔵 Upcoming (next 7 days)',
    dash_reminders:       '🔔 Reminders',
    dash_pending:         'pending',
    dash_viewAll:         'View all →',
    dash_markDone:        'Mark done',
    dash_pipeline:        'Pipeline Progress',
    dash_records:         'records',
    dash_recentActivity:  'Recent Activity',
    dash_noActivity:      'No recent activity.',

    // Table
    table_img:            'IMG',
    table_ref:            'Ref',
    table_product:        'Product',
    table_type:           'Type',
    table_brand:          'Brand',
    table_property:       'Property',
    table_stage:          'Stage',
    table_priority:       'Priority',
    table_owner:          'Owner',
    table_waiting:        'Waiting',
    table_nextAction:     'Next Action',
    table_samples:        'Samples',
    table_reminder:       'Reminder',
    table_noRecords:      'No records match your filters.',
    table_search:         'Search records…',
    table_allBrands:      'All Brands',
    table_allProperties:  'All Properties',
    table_allStages:      'All Stages',
    table_allOwners:      'All Owners',
    table_allPriorities:  'All Priorities',
    table_waitingOn:      'Waiting On',
    table_showArchived:   'Archived',
    table_showReminders:  'Reminders',
    table_exportCSV:      'Export CSV',
    table_newRecord:      '+ New Record',

    // Settings
    settings_title:       'System Settings',
    settings_subtitle:    'Admin-only controls for automated features.',
    settings_emailAuto:   'Email Automation',
    settings_loading:     'Loading…',
    settings_reminderLabel: 'Daily Reminder Emails',
    settings_reminderHint:  'Send automatic email reminders to record owners at 9:00 AM every day for due or overdue reminders.',
    settings_on:          'On',
    settings_off:         'Off',
    settings_howTitle:    'How it works:',
    settings_howText:     'Every day at 9:00 AM, CodiFlow checks for records with a reminder date that is today or overdue. Each record owner receives an individual email listing the reminder. Turn this off to stop all automated reminder emails.',
    settings_save:        'Save Settings',
    settings_saving:      'Saving…',
    settings_saved:       '✓ Saved!',
  },

  fr: {
    // Nav
    nav_navigate:    'Navigation',
    nav_dashboard:   'Tableau de bord',
    nav_board:       'Kanban',
    nav_table:       'Tableau',
    nav_approved:    'Approuvé',
    nav_samples:     'Échantillons',
    nav_team:        'Équipe',
    nav_profile:     'Profil',
    nav_templates:   'Modèles',
    nav_settings:    'Paramètres',
    nav_newRecord:   '+ Nouvel enregistrement',
    nav_signOut:     'Quitter',

    // Record Drawer
    drawer_details:       'Détails',
    drawer_comments:      'Commentaires',
    drawer_history:       'Historique',
    drawer_edit:          '✏️ Modifier',
    drawer_notify:        '✉ Notifier',
    drawer_archive:       '📁 Archiver',
    drawer_restore:       '📤 Restaurer',
    drawer_archived:      '📁 Archivé',
    drawer_moveStage:     'CHANGER DE STADE',
    drawer_priority:      'PRIORITÉ',
    drawer_waitingOn:     'En attente de :',
    drawer_notes:         'NOTES',
    drawer_feedback:      'RETOUR LICENCIER',
    drawer_attachments:   'PIÈCES JOINTES',
    drawer_upload:        '+ Téléverser',
    drawer_uploading:     'Téléversement…',
    drawer_cover:         'COUVERTURE',
    drawer_setCover:      '⭐ Couverture',
    drawer_open:          'Ouvrir ↗',
    drawer_addComment:    'Ajouter un commentaire…',
    drawer_post:          'Publier',
    drawer_noComments:    'Aucun commentaire pour l\'instant.',
    drawer_noHistory:     'Aucun historique pour l\'instant.',
    drawer_brand:         'Marque',
    drawer_property:      'Propriété',
    drawer_productType:   'Type de produit',
    drawer_gender:        'Genre',
    drawer_owner:         'Propriétaire',
    drawer_contact:       'Contact',
    drawer_licensorRef:   'Réf. Licencier',
    drawer_samples:       'Échantillons',
    drawer_submission:    'Soumission',
    drawer_conceptApproval: 'Approbation concept',
    drawer_ppsPhotos:     'Photos PPS',
    drawer_ppsApproval:   'Approbation PPS',
    drawer_sampleSent:    'Échantillon envoyé',
    drawer_sampleApproval:'Approbation échantillon',
    drawer_techPack:      'Fiche technique',
    drawer_additionalLink:'Lien supplémentaire',
    drawer_deleteConfirm: 'Supprimer cet enregistrement ? Cette action est irréversible.',
    drawer_system:        'Système',

    // Record Form
    form_internalRef:     'Référence interne *',
    form_licensorRef:     'Réf. licencier principale',
    form_productName:     'Nom du produit *',
    form_productType:     'Type de produit',
    form_gender:          'Genre',
    form_brand:           'Marque',
    form_property:        'Propriété',
    form_stage:           'Stade',
    form_priority:        'Priorité',
    form_owner:           'Propriétaire',
    form_waitingOn:       'En attente de',
    form_contact:         'Contact',
    form_nextAction:      'Prochaine action',
    form_notes:           'Notes',
    form_feedback:        'Retour du licencier',
    form_techPackLink:    'Lien fiche technique',
    form_additionalLink:  'Lien supplémentaire',
    form_submissionDate:  'Date de soumission',
    form_samplesQty:      'Qté d\'échantillons',
    form_reminder:        '🔔 Rappel de suivi',
    form_reminderDate:    'Date de rappel',
    form_reminderNote:    'Note (optionnelle)',
    form_reminderDone:    'Marquer le rappel comme terminé',
    form_unassigned:      '— Non assigné —',
    form_select:          '— Sélectionner —',
    form_addBrand:        '＋ Ajouter une marque…',
    form_addProperty:     '＋ Ajouter une propriété…',
    form_typeBrand:       'Entrer le nom de la marque…',
    form_typeProperty:    'Entrer le nom de la propriété…',
    form_reminderPlaceholder: 'ex. Relancer le licencier pour approbation',
    form_attachClick:     'Cliquez pour joindre des images ou fichiers',
    form_attachSub:       'Sera téléversé lors de la sauvegarde',
    form_attachments:     'PIÈCES JOINTES',
    form_uploadFile:      '＋ Joindre un fichier',
    form_uploading:       'Téléversement…',
    form_save:            'Enregistrer',
    form_saving:          'Enregistrement…',
    form_cancel:          'Annuler',

    // Dashboard
    dash_activeRecords:   'Dossiers actifs',
    dash_fullyApproved:   'Entièrement approuvés',
    dash_remindersDue:    'Rappels dus',
    dash_upcomingWeek:    'à venir cette semaine',
    dash_noUpcoming:      'Aucun rappel à venir',
    dash_awaitingLicensor:'En attente du licencier',
    dash_awaitingFull:    'en attente d\'approbation',
    dash_overdue:         '🔴 En retard',
    dash_dueToday:        '🟡 Pour aujourd\'hui',
    dash_upcoming:        '🔵 Prochains (7 jours)',
    dash_reminders:       '🔔 Rappels',
    dash_pending:         'en attente',
    dash_viewAll:         'Voir tout →',
    dash_markDone:        'Marquer fait',
    dash_pipeline:        'Progression du pipeline',
    dash_records:         'dossiers',
    dash_recentActivity:  'Activité récente',
    dash_noActivity:      'Aucune activité récente.',

    // Table
    table_img:            'IMG',
    table_ref:            'Réf',
    table_product:        'Produit',
    table_type:           'Type',
    table_brand:          'Marque',
    table_property:       'Propriété',
    table_stage:          'Stade',
    table_priority:       'Priorité',
    table_owner:          'Propriétaire',
    table_waiting:        'En attente',
    table_nextAction:     'Prochaine action',
    table_samples:        'Échantillons',
    table_reminder:       'Rappel',
    table_noRecords:      'Aucun dossier ne correspond aux filtres.',
    table_search:         'Rechercher…',
    table_allBrands:      'Toutes les marques',
    table_allProperties:  'Toutes les propriétés',
    table_allStages:      'Tous les stades',
    table_allOwners:      'Tous les propriétaires',
    table_allPriorities:  'Toutes les priorités',
    table_waitingOn:      'En attente de',
    table_showArchived:   'Archivés',
    table_showReminders:  'Rappels',
    table_exportCSV:      'Exporter CSV',
    table_newRecord:      '+ Nouveau dossier',

    // Settings
    settings_title:       'Paramètres système',
    settings_subtitle:    'Contrôles réservés aux administrateurs.',
    settings_emailAuto:   'Automatisation des e-mails',
    settings_loading:     'Chargement…',
    settings_reminderLabel: 'E-mails de rappel quotidiens',
    settings_reminderHint:  'Envoyer des rappels automatiques aux propriétaires de dossiers à 9h00 chaque jour pour les rappels dus ou en retard.',
    settings_on:          'Activé',
    settings_off:         'Désactivé',
    settings_howTitle:    'Comment ça fonctionne :',
    settings_howText:     'Chaque jour à 9h00, CodiFlow vérifie les dossiers dont la date de rappel est arrivée ou dépassée. Chaque propriétaire reçoit un e-mail individuel. Désactivez pour stopper tous les e-mails automatiques de rappel.',
    settings_save:        'Enregistrer',
    settings_saving:      'Enregistrement…',
    settings_saved:       '✓ Enregistré !',
  },
}

export type Translations = typeof T['en']

// ── Context ────────────────────────────────────────────────────────────────────
interface LangCtx { lang: Lang; setLang: (l: Lang) => void; t: Translations }
const Ctx = createContext<LangCtx>({ lang: 'en', setLang: () => {}, t: T.en })

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const [lang, setLangState] = useState<Lang>('en')

  useEffect(() => {
    const stored = localStorage.getItem('codi_lang') as Lang | null
    if (stored === 'en' || stored === 'fr') setLangState(stored)
  }, [])

  function setLang(l: Lang) {
    setLangState(l)
    localStorage.setItem('codi_lang', l)
  }

  return <Ctx.Provider value={{ lang, setLang, t: T[lang] }}>{children}</Ctx.Provider>
}

export function useLanguage() {
  return useContext(Ctx)
}
